name: Actualització Manual de GeoJSONs

on:
  workflow_dispatch: # Activa el botó d'execució manual a la web de GitHub

jobs:
  proces_actualitzacio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codi
        uses: actions/checkout@v4

      - name: Configurar entorn Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instal·lar llibreries
        run: pip install pandas requests

      - name: Executar script de descàrrega
        run: python descarregar_dades.py

      - name: Guardar canvis al GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dades/*.geojson
          git commit -m "Actualització manual de dades GeoJSON: $(date +'%Y-%m-%d')" || echo "Sense canvis per pujar"
          git push
